typography_spectrum: 1
color:
  brandColors:
    - '#fefefe'
    - '#a8b1a9'
    - '#2c2c1f'
    - '#81a700'
    - '#ff5343'
  brandStrength: 0.25
  lightness: 0.2776059955358505
  saturation: 0.5625
  rhythmicContrast: 0.36881888075731695
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8897
analytics:
  google: null
  facebook: null
  twitter: null
name: Garcia + Garcia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 2 Garcias y 1/2
description: Bitacora del Viaje Eterno
purpose: []
