layout_spectrum: 0.5678078103810549
typography_spectrum: 0.3503010426647961
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.9934564949944615
  lightness: 0.07162087317556143
  saturation: 0.39254951709881425
  rhythmicContrast: 0.6530637601390481
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Garcia + Garcia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 2 Garcias y 1/2
description: Bitacora del Viaje Eterno
purpose: []
