name: Garcia + Garcia
favicon: null
layout_spectrum: 0.8897
typography_spectrum: 1
title: 2 Garcias
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#a8b1a9'
    - '#2c2c1f'
    - '#81a700'
    - '#ff5343'
  brandStrength: 0.25
  lightness: 0.2776059955358505
  saturation: 0.5625
  rhythmicContrast: 0.36881888075731695
purpose: []
